# basefolder to store hub in
project_folder: /local/home/endrebak/code/biocore/create_trackhub/ECSeq

# sample sheet
sample_sheet: sample_sheet.txt

# genomes:
genomes:
  - rn6

################
# hub settings #
################

hub_name: ECSeq
short_hub_label: ECSeq
long_hub_label: Transcriptional atlas of layer II and deep layers in medial and lateral entorhinal cortex (EC) during postnatal development of rats.
email: endrebak85@gmail.com

# optional
hub_description_url: http://address_to_webpage_with_track.info

################
# track header #
################

# can often be the same as the hub_name
supertrack: ECSeq

# Name that is unimportant?
supertrack_group: regulation

short_label_supertrack: EC RNA-Seq
long_label_supertrack: RNA-seq data of sub-regions from micro-dissected rat entorhinal cortex (EC), sampled at postnatal day (P) P2, P9, P23, and P45.

##################
# group settings #
##################

group:
  reverse:
    short_label: HaCaT TT RNA-Seq
    long_label: RNA-seq reads mapping to reverse
  forward:
    short_label: HaCaT TT RNA-Seq
    long_label: RNA-seq reads mapping to forward
